import { Product, BlogPost, Category } from './types';

export const categories: Category[] = [
  { id: 'zdravlje-prostate', name: 'Zdravlje prostate' },
  { id: 'kosti-zglobovi-misici', name: 'Kosti, zglobovi i mišići' },
  { id: 'mrsavljenje', name: 'Mršavljenje' },
];

export const products: Product[] = [
  {
    id: 'urasan-forte-30',
    categoryId: 'zdravlje-prostate',
    name: 'Urasan Forte',
    packaging: '30 kapsula',
    shortDescription: 'Zdravlje urološkog sustava.',
    price: 19.99,
    benefits: ['Podržava prostatu', 'Smanjuje tegobe', 'Prirodni ekstrakti'],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edb7999742af?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'urasan-forte-60',
    categoryId: 'zdravlje-prostate',
    name: 'Urasan Forte',
    packaging: '60 kapsula',
    shortDescription: 'Zdravlje urološkog sustava.',
    price: 34.99,
    benefits: ['Podržava prostatu', 'Smanjuje tegobe', 'Prirodni ekstrakti'],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edb7999742af?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'kurkuma-forte-30',
    categoryId: 'kosti-zglobovi-misici',
    name: 'Kurkuma Forte',
    packaging: '30 kapsula',
    shortDescription: 'Snažan antioksidans za vaše zglobove.',
    price: 18.99,
    benefits: ['Smanjuje upale', 'Poboljšava fleksibilnost', 'Jak antioksidans'],
    imageUrl: 'https://images.unsplash.com/photo-1611078482436-11f8b4dc62f7?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'kurkuma-forte-60',
    categoryId: 'kosti-zglobovi-misici',
    name: 'Kurkuma Forte',
    packaging: '60 kapsula',
    shortDescription: 'Snažan antioksidans za vaše zglobove.',
    price: 32.99,
    benefits: ['Smanjuje upale', 'Poboljšava fleksibilnost', 'Jak antioksidans'],
    imageUrl: 'https://images.unsplash.com/photo-1611078482436-11f8b4dc62f7?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'kurkuma-cream-cold-225',
    categoryId: 'kosti-zglobovi-misici',
    name: 'Kurkuma Cream Cold',
    packaging: '225 ml',
    shortDescription: 'Hladni gel za ublažavanje mišićne boli.',
    price: 24.99,
    benefits: ['Efekt hlađenja', 'Osvježava mišiće', 'Lako se upija'],
    imageUrl: 'https://images.unsplash.com/photo-1556228578-8d89f187a412?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'kurkuma-cream-cold-100',
    categoryId: 'kosti-zglobovi-misici',
    name: 'Kurkuma Cream Cold',
    packaging: '100 ml',
    shortDescription: 'Hladni gel za ublažavanje mišićne boli.',
    price: 14.99,
    benefits: ['Efekt hlađenja', 'Osvježava mišiće', 'Lako se upija'],
    imageUrl: 'https://images.unsplash.com/photo-1556228578-8d89f187a412?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'kurkuma-cream-hot-225',
    categoryId: 'kosti-zglobovi-misici',
    name: 'Kurkuma Cream Hot',
    packaging: '225 ml',
    shortDescription: 'Topla krema za opuštanje zglobova i mišića.',
    price: 24.99,
    benefits: ['Efekt zagrijavanja', 'Opušta zglobove', 'Umiruje napetost'],
    imageUrl: 'https://images.unsplash.com/photo-1608222351212-18fe0ec7b13b?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'kurkuma-cream-hot-100',
    categoryId: 'kosti-zglobovi-misici',
    name: 'Kurkuma Cream Hot',
    packaging: '100 ml',
    shortDescription: 'Topla krema za opuštanje zglobova i mišića.',
    price: 14.99,
    benefits: ['Efekt zagrijavanja', 'Opušta zglobove', 'Umiruje napetost'],
    imageUrl: 'https://images.unsplash.com/photo-1608222351212-18fe0ec7b13b?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'citrax-forte-30',
    categoryId: 'mrsavljenje',
    name: 'Citrax Forte',
    packaging: '30 kapsula',
    shortDescription: 'Prirodna pomoć pri mršavljenju.',
    price: 15.99,
    benefits: ['Ubrzava metabolizam', 'Podiže energiju', 'Sagorijeva masti'],
    imageUrl: 'https://images.unsplash.com/photo-1584305581561-bd3d10072b21?auto=format&fit=crop&q=80&w=400&h=400',
  },
  {
    id: 'citrax-forte-60',
    categoryId: 'mrsavljenje',
    name: 'Citrax Forte',
    packaging: '60 kapsula',
    shortDescription: 'Prirodna pomoć pri mršavljenju.',
    price: 27.99,
    benefits: ['Ubrzava metabolizam', 'Podiže energiju', 'Sagorijeva masti'],
    imageUrl: 'https://images.unsplash.com/photo-1584305581561-bd3d10072b21?auto=format&fit=crop&q=80&w=400&h=400',
  }
];

export const blogPosts: BlogPost[] = [
  {
    id: 'post-1',
    title: 'Kako kurkuma pomaže vašim zglobovima?',
    excerpt: 'Saznajte sve o nevjerojatnim protuupalnim svojstvima kurkume i kako može poboljšati vašu pokretljivost.',
    content: 'Kurkuma, začin duboko žute boje koji se tradicionalno koristi u indijskoj kuhinji i ayurvedskoj medicini, dobiva sve više pažnje u suvremenoj znanosti zbog svojih moćnih protuupalnih svojstava. Glavni aktivni sastojak kurkume, kurkumin, dokazano djeluje na molekularnoj razini, boreći se protiv upala koje su u pozadini brojnih kroničnih bolesti, uključujući i bolesti zglobova poput osteoartritisa i reumatoidnog artritisa.\n\nJedan od glavnih izazova kod kurkumina je njegova niska bioraspoloživost. To znači da se teško apsorbira u krvotok iz probavnog trakta. Zbog toga se u kvalitetnim dodacima prehrani kurkumin često kombinira s ekstraktom crnog papra (piperinom), koji dokazano povećava apsorpciju kurkumina za čak 2000%.\n\nOsim što djeluje protuupalno, kurkumin je i snažan antioksidans koji neutralizira slobodne radikale, smanjujući oksidativni stres u tijelu. Redovitom konzumacijom visokokvalitetnih suplemenata s kurkumom možete osjetiti značajno olakšanje u zglobovima, povećanu pokretljivost te smanjenje jutarnje ukočenosti.',
    imageUrl: 'https://images.unsplash.com/photo-1615486171430-84358a9e1e32?auto=format&fit=crop&q=80&w=600&h=400',
    date: '10. Listopada 2023.',
  },
  {
    id: 'post-2',
    title: '5 savjeta za prirodno mršavljenje',
    excerpt: 'Otkrijte kako na zdrav i prirodan način doći do željene težine uz pomoć pravih dodataka prehrani.',
    content: 'Mršavljenje ne mora značiti rigorozne dijete i iscrpljujuće treninge. Ključ trajnog gubitka težine leži u postepenim promjenama životnih navika i pametnom korištenju prirodnih dodataka prehrani koji podržavaju vaš metabolizam. Evo naših 5 ključnih savjeta za prirodno i zdravo mršavljenje.\n\n1. Hidratacija je ključ: Voda ubrzava metabolizam i pomaže u eliminaciji toksina. Često brkamo osjećaj žeđi s osjećajem gladi, stoga pokušajte popiti čašu vode kada osjetite naglu potrebu za grickalicama.\n2. Birajte cjelovite namirnice: Fokusirajte se na hranu bogatu vlaknima poput povrća, voća, mahunarki i cjelovitih žitarica. Vlakna vas duže drže sitima i reguliraju razinu šećera u krvi.\n3. Uključite proteine u svaki obrok: Proteini zahtijevaju više energije za probavu (termički efekt hrane) i čuvaju mišićnu masu tijekom mršavljenja.\n4. San je važniji nego što mislite: Nedostatak sna remeti hormone gladi (grelin i leptin), povećavajući želju za visokokaloričnom hranom.\n5. Pametno koristite dodatke prehrani: Prirodni sagorijevači masti na bazi citrusa, zelenog čaja ili L-karnitina mogu ubrzati vaš metabolizam i dati vam dodatnu energiju za svakodnevne aktivnosti. Naš Citrax Forte formuliran je upravo s tim ciljem - podrška vašem metabolizmu iz prirode.',
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&q=80&w=600&h=400',
    date: '02. Rujna 2023.',
  },
  {
    id: 'post-3',
    title: 'Zašto je zdravlje prostate važno',
    excerpt: 'Preventiva je ključ. Pročitajte naše savjete za održavanje zdravog urološkog sustava.',
    content: 'Prostata je mala žlijezda koja igra bitnu ulogu u muškom reproduktivnom sustavu, no mnogi muškarci ne obraćaju pažnju na njeno zdravlje sve dok se ne pojave prvi simptomi povećane prostate. Benigna hiperplazija prostate (BHP) česta je pojava kod muškaraca iznad 50 godina, a simptomi uključuju često mokrenje, otežan protok i osjećaj nepotpunog pražnjenja mjehura.\n\nRedoviti pregledi od iznimne su važnosti za rano otkrivanje problema, no postoje i brojni prirodni načini za proaktivnu brigu o zdravlju prostate. Uravnotežena prehrana bogata rajčicama (likopen), orašastim plodovima, sjemenkama bundeve te smanjen unos crvenog mesa i prerađenih namirnica čine odličan temelj.\n\nKada je riječ o dodacima prehrani, biljni ekstrakti poput ploda sabal palme (Saw Palmetto) i sjemenki bundeve tradicionalno se koriste za ublažavanje simptoma povećane prostate. Naš proizvod Urasan Forte idealna je kombinacija biljnih ekstrakata dizajnirana da olakša tegobe urološkog sustava i vrati vam noćni mir.',
    imageUrl: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?auto=format&fit=crop&q=80&w=600&h=400',
    date: '15. Kolovoza 2023.',
  }
];
